# Generated by Django 2.1.2 on 2018-12-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
