# Generated by Django 2.1.2 on 2019-01-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='footer_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='homepage_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='page_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
