# Generated by Django 2.1.2 on 2019-01-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settings_mourning_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='left_column_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
