# Generated by Django 2.1.2 on 2018-11-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='answer',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
