# Generated by Django 2.1.2 on 2018-12-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travel_promotion_on_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.Travel')),
            ],
        ),
    ]
