# Generated by Django 2.1.2 on 2018-12-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_travelimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelimage',
            old_name='property',
            new_name='travel',
        ),
        migrations.AlterField(
            model_name='travelimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
