# Generated by Django 2.1.2 on 2018-12-27 21:10

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20181223_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='country',
            field=django_countries.fields.CountryField(default='PL', max_length=746, multiple=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
