# Generated by Django 2.1.2 on 2018-12-27 21:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20181227_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
