# Generated by Django 2.1.2 on 2018-12-27 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20181227_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 21, 58, 40, 429492, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='travel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 21, 58, 40, 429458, tzinfo=utc)),
        ),
    ]
