# Generated by Django 2.1.2 on 2019-01-05 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20181227_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 21, 14, 15, 39651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 21, 14, 15, 39618, tzinfo=utc)),
        ),
    ]
