# Generated by Django 2.1.2 on 2019-01-05 21:22

import cms.apps.travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20190105_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_date',
            field=models.DateTimeField(default=cms.apps.travel.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_date',
            field=models.DateTimeField(default=cms.apps.travel.models.default_start_date),
        ),
    ]
