# Generated by Django 2.1.2 on 2019-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20190105_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='passengers_limit',
            field=models.IntegerField(default=20),
        ),
    ]
