# Generated by Django 2.1.2 on 2019-03-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_travel_passengers_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='rejections',
            field=models.IntegerField(default=0),
        ),
    ]
