# Generated by Django 2.1.2 on 2019-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_travel_rejections'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='discount_per_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travel',
            name='max_discount',
            field=models.IntegerField(default=0),
        ),
    ]
