# Generated by Django 2.1.2 on 2019-03-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_auto_20190305_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='discount_per_person',
            field=models.IntegerField(default=0, verbose_name='Discount per person (%)'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='max_discount',
            field=models.IntegerField(default=0, verbose_name='Max discount per travel (%)'),
        ),
    ]
